// <auto-generated />
using System;
using GerenciarCardapio.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GerenciarCardapio.Migrations
{
    [DbContext(typeof(ComandaContext))]
    partial class ComandaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GerenciarCardapio.Models.CategoriaProdutos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NomeCategoria")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("CategoriaProdutos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeCategoria = "Comidas"
                        },
                        new
                        {
                            Id = 2,
                            NomeCategoria = "Cervejas"
                        },
                        new
                        {
                            Id = 3,
                            NomeCategoria = "Drinks"
                        },
                        new
                        {
                            Id = 4,
                            NomeCategoria = "Cachaças"
                        });
                });

            modelBuilder.Entity("GerenciarCardapio.Models.Comanda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataComandaAbriu")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataComandaFechada")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentificacaoCliente")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Comandas");
                });

            modelBuilder.Entity("GerenciarCardapio.Models.ComandaProduto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ComandaId")
                        .HasColumnType("int");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.HasIndex("ProdutoId");

                    b.ToTable("ProdutosComandas");
                });

            modelBuilder.Entity("GerenciarCardapio.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<bool?>("Estoque")
                        .HasColumnType("bit");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("QuantidadeEstoque")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("GerenciarCardapio.Models.ComandaProduto", b =>
                {
                    b.HasOne("GerenciarCardapio.Models.Comanda", "Comanda")
                        .WithMany("ComandaProdutos")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GerenciarCardapio.Models.Produto", "Produto")
                        .WithMany("ComandaProdutos")
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comanda");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("GerenciarCardapio.Models.Produto", b =>
                {
                    b.HasOne("GerenciarCardapio.Models.CategoriaProdutos", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("GerenciarCardapio.Models.CategoriaProdutos", b =>
                {
                    b.Navigation("Produtos");
                });

            modelBuilder.Entity("GerenciarCardapio.Models.Comanda", b =>
                {
                    b.Navigation("ComandaProdutos");
                });

            modelBuilder.Entity("GerenciarCardapio.Models.Produto", b =>
                {
                    b.Navigation("ComandaProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
